import { Candidate } from "./types";

export const mockCandidatesData: Candidate[] = [
  {
    id: "1",
    name: "Liam Chen",
    email: "Liamchen@mail.com",
    role: "Product Designer",
    status: "Ongoing",
    date: "May 14, 2026",
    score: 0,
    action: "empty",
  },
  {
    id: "2",
    name: "Maria Gonzalez",
    email: "maria.g@gmail.com",
    role: "UX Researcher",
    status: "Ongoing",
    date: "June 2, 2026",
    score: 84,
    action: "Recommended",
  },
  {
    id: "3",
    name: "Raj Patel",
    email: "raj.patel@yahoo.com",
    role: "Visual Designer",
    status: "Needs review",
    date: "April 28, 2026",
    score: 0,
    action: "None",
  },
  {
    id: "4",
    name: "Anika Roberts",
    email: "anika.r@gmail.com",
    role: "Interaction Designer",
    status: "Completed",
    date: "May 30, 2026",
    score: 77,
    action: "Recommended",
  },
  {
    id: "5",
    name: "Noah Kim",
    email: "noah.kim@mail.com",
    role: "UX Engineer",
    status: "Completed",
    date: "June 10, 2026",
    score: 69,
    action: "Maybe",
  },
];
